let questions = [
    {
        question: "Which of these claims is accurate?",
        options: [
            { text: "The Great Wall of China is visible from space.", correct: false },
            { text: "The Great Wall of China can only be seen from low Earth orbit with the naked eye.", correct: false },
            { text: "No one has ever managed to see the Great Wall of China from space.", correct: true }
        ],
        tip: "Many people think you can see the Great Wall from space, but it’s actually too small! Always check if the claim makes sense."
    },
    {
        question: "Which image was generated by AI?",
        options: [
            { text: "AI-generated Image", correct: true },
            { text: "Human-drawn Image", correct: false },
            { text: "Real image of a person", correct: false }
        ],
        tip: "AI images can look real, but sometimes you can spot things like weird shadows or strange faces. If something looks off, it probably is!"
    },
    {
        question: "Is this response from AI correct?",
        options: [
            { text: "AI has already surpassed human intelligence.", correct: false },
            { text: "AI will be able to solve all human problems by 2030.", correct: false },
            { text: "AI can assist in tasks but is still far from surpassing human intelligence.", correct: true }
        ],
        tip: "AI is good at helping us, but it doesn’t have the creativity and critical thinking of humans. When AI makes big claims, ask: ‘Can it really do that?’"
    }
];

let currentQuestionIndex = 0;

function startGame(ageGroup) {
    document.querySelector('#intro-page').style.display = 'none';
    document.getElementById('game-container').style.display = 'block';
    showQuestion();
}

function showQuestion() {
    let question = questions[currentQuestionIndex];
    let questionContainer = document.getElementById('question-container');
    questionContainer.innerHTML = `<p>${question.question}</p>`;
    
    let optionsHtml = '';
    question.options.forEach((option, index) => {
        optionsHtml += `<button onclick="checkAnswer(${index})">${option.text}</button>`;
    });
    
    questionContainer.innerHTML += optionsHtml;
}

function checkAnswer(index) {
    let question = questions[currentQuestionIndex];
    let feedbackContainer = document.getElementById('feedback-container');
    if (question.options[index].correct) {
        feedbackContainer.innerHTML = "<p>Correct!</p>";
        document.getElementById('next-button').style.display = 'block';
    } else {
        feedbackContainer.innerHTML = "<p>Oops, that's incorrect. Try again!</p>";
    }
}

function nextQuestion() {
    currentQuestionIndex++;
    if (currentQuestionIndex < questions.length) {
        showQuestion();
        document.getElementById('next-button').style.display = 'none';
    } else {
        finishGame();
    }
}

function finishGame() {
    document.getElementById('game-container').style.display = 'none';
    document.getElementById('end-game').style.display = 'block';
}

function proceedToConsent() {
    document.getElementById('end-game').style.display = 'none';
    document.getElementById('consent-page').style.display = 'block';
}

function generateBadge() {
    // Show the badge image
    let badgeImage = document.createElement('img');
    badgeImage.src = 'badge.png';  // Path to the badge image

    // Set the badge size to be smaller (adjust width and height as needed)
    badgeImage.style.width = '70px';  // Set the width of the badge
    badgeImage.style.height = '70px';  // Maintain aspect ratio

    // Display the badge
    document.getElementById('badge-section').style.display = 'block';
    document.getElementById('badge-section').appendChild(badgeImage);

    // Create a download button for the badge
    let downloadButton = document.getElementById('badge-download');
    downloadButton.href = 'badge.png';
    downloadButton.download = 'AI_Detective_Badge.png';
    downloadButton.innerHTML = 'Download Your Badge';
}
